bug fix

diff --git a/.github/workflows/manage_osn_manila.yml b/.github/workflows/manage_osn_manila.yml
--- a/.github/workflows/manage_osn_manila.yml
+++ b/.github/workflows/manage_osn_manila.yml
@@ -73,28 +73,29 @@ jobs:
         run: |
             mkdir -p /tmp/osn_bucket/
 
+            NEW_DATA=$(rclone lsd osn_sdsc_ubna:bio230143-bucket01 | sort | tail -n 1| awk '{print $NF}')
+
             # Step 2: Mount the OSN bucket using rclone (with daemon option)
-            rclone mount osn_sdsc_ubna:bio230143-bucket01 /tmp/osn_bucket/ --daemon
+            rclone mount "osn_sdsc_ubna:bio230143-bucket01$NEW_DATA/" /tmp/osn_bucket/ --daemon
 
             # Step 3: Add a short delay to ensure the mount has completed (optional)
             sleep 200  # Adjust sleep time as necessary to give rclone time to mount
 
-            NEW_DATA=$(rclone lsd osn_sdsc_ubna:bio230143-bucket01 | sort | tail -n 1| awk '{print $NF}')
-
             # Step 4: Get the most recent directory or file to process (assuming NEW_DATA is set elsewhere)
-            NEW_DATA_PATH="/tmp/osn_bucket/$NEW_DATA/"
-            
+            #NEW_DATA_PATH="/tmp/osn_bucket/$NEW_DATA/"
+            CONTENTS = $(ls /tmp/osn_bucket/)
+            echo $CONTENTS
             # Step 5: Print the NEW_DATA_PATH to check if it's correct
-            echo "Checking path: $NEW_DATA_PATH/"
+            #echo "Checking path: $NEW_DATA_PATH/"
             
             # Step 6: Ensure the file exists and is accessible
-            if [[ ! -d "$NEW_DATA_PATH" ]]; then  # Use -d to check for directories
-                echo "Error: Data directory not found: $NEW_DATA_PATH"
-                exit 1
-            fi
+            #if [[ ! -d "$NEW_DATA_PATH" ]]; then  # Use -d to check for directories
+                #echo "Error: Data directory not found: $NEW_DATA_PATH"
+                #exit 1
+            #fi
             
             # Step 7: Run the Docker container with the mounted OSN bucket file
-            docker run -v "$NEW_DATA_PATH":/app/recordings_2023/ buzzfindr-image:latest
+            docker run -v /tmp/osn_bucket/:/app/recordings_2023/ buzzfindr-image:latest
             
             # Clean up (optional, unmount the rclone mount)
             umount /tmp/osn_bucket/
